arabic-reshaper==3.0.0
asgiref==3.8.1
asn1crypto==1.5.1
certifi==2024.8.30
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==43.0.1
cssselect2==0.7.0
Django==5.1.1
html5lib==1.1
idna==3.8
lxml==5.3.0
oscrypto==1.3.0
pillow==10.4.0
pycparser==2.22
pyHanko==0.25.1
pyhanko-certvalidator==0.26.3
PyMySQL==1.1.1
pypdf==4.3.1
pypng==0.20220715.0
python-bidi==0.6.0
PyYAML==6.0.2
qrcode==7.4.2
reportlab==4.2.2
requests==2.32.3
six==1.16.0
sqlparse==0.5.1
svglib==1.5.1
tinycss2==1.3.0
typing_extensions==4.12.2
tzdata==2024.1
tzlocal==5.2
uritools==4.0.3
urllib3==2.2.2
webencodings==0.5.1
xhtml2pdf==0.2.16



Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\smartparkig\smartparking\Lib\site-packages\django\core\checks\urls.py", line 136, in check_custom_error_handlers
    handler = resolver.resolve_error_handler(status_code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\smartparkig\smartparking\Lib\site-packages\django\urls\resolvers.py", line 732, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\smartparkig\smartparking\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\smartparkig\smartparking\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\smartparkig\smartparking\SmartParking\SmartParking\urls.py", line 5, in <module>
    from Reserva import views
  File "C:\smartparkig\smartparking\SmartParking\Reserva\views.py", line 5, in <module>
    from .forms import RegisterForm,RegisterVehiculosforms,RegisterTarjetasforms,RegiserExtendUser,Reservaforms
  File "C:\smartparkig\smartparking\SmartParking\Reserva\forms.py", line 13, in <module>
    from .utils import calculadora
  File "C:\smartparkig\smartparking\SmartParking\Reserva\utils.py", line 3, in <module>
    from xhtml2pdf import pisa
  File "C:\smartparkig\smartparking\Lib\site-packages\xhtml2pdf\pisa.py", line 26, in <module>
    from xhtml2pdf.document import pisaDocument
  File "C:\smartparkig\smartparking\Lib\site-packages\xhtml2pdf\document.py", line 19, in <module>
    from reportlab.lib import pdfencrypt
  File "C:\smartparkig\smartparking\Lib\site-packages\reportlab\lib\pdfencrypt.py", line 11, in <module>
    from reportlab.lib.utils import asBytes, int2Byte, rawBytes, asNative
  File "C:\smartparkig\smartparking\Lib\site-packages\reportlab\lib\utils.py", line 15, in <module>
    from PIL import Image
ImportError: cannot import name 'Image' from 'PIL' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\smartparkig\smartparking\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\smartparkig\smartparking\Lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "C:\smartparkig\smartparking\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\smartparkig\smartparking\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\smartparkig\smartparking\Lib\site-packages\django\core\checks\urls.py", line 138, in check_custom_error_handlers
    path = getattr(resolver.urlconf_module, "handler%s" % status_code)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\smartparkig\smartparking\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\smartparkig\smartparking\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\smartparkig\smartparking\SmartParking\SmartParking\urls.py", line 5, in <module>
    from Reserva import views
  File "C:\smartparkig\smartparking\SmartParking\Reserva\views.py", line 5, in <module>
    from .forms import RegisterForm,RegisterVehiculosforms,RegisterTarjetasforms,RegiserExtendUser,Reservaforms
  File "C:\smartparkig\smartparking\SmartParking\Reserva\forms.py", line 13, in <module>
    from .utils import calculadora
  File "C:\smartparkig\smartparking\SmartParking\Reserva\utils.py", line 3, in <module>
    from xhtml2pdf import pisa
  File "C:\smartparkig\smartparking\Lib\site-packages\xhtml2pdf\pisa.py", line 26, in <module>
    from xhtml2pdf.document import pisaDocument
  File "C:\smartparkig\smartparking\Lib\site-packages\xhtml2pdf\document.py", line 19, in <module>
    from reportlab.lib import pdfencrypt
  File "C:\smartparkig\smartparking\Lib\site-packages\reportlab\lib\pdfencrypt.py", line 11, in <module>
    from reportlab.lib.utils import asBytes, int2Byte, rawBytes, asNative
  File "C:\smartparkig\smartparking\Lib\site-packages\reportlab\lib\utils.py", line 15, in <module>
    from PIL import Image
ImportError: cannot import name 'Image' from 'PIL' (unknown location)

